Feat/#15 user authentication
scoala-online/main pull request #48
Opened 2021-09-19 11:38 UTC by MarianGiugioiu

### This pull request solves issue:

Issue: #15 

### Which app is this issue related to?

- [x] REST API
- [ ] E-Learning React App
- [ ] ~~Admin Panel~~ - Not created yet

### Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Wiki Updates

- [ ] No need for updates
- [x] Requires an update ( _not done within this issue_ )
- [ ] Has been updated ( _done within this issue_ )

### Testing checklist

- [ ] Unit tests
- [ ] Functional tests
- [ ] E2E tests

#### Compatibility tests - **_For E-Learning React App Only_**

- [ ] Tested on Safari
- [ ] Tested on Chrome
- [ ] Tested on Mozilla Firefox

### What changes have been done within this issue?

### How should this be manually tested?

### Screenshots or example usage

2021-09-23 18:42 UTC, CristiPV requested changes

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/DTO/RegisterForm.java
> +  private String Name;
Change 'Name' to 'name' and make sure to change it in all the places where it is used.

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/RoleController.java
> +   * @return a Response Entity with HTTP Status OK and a list of the User entries.
```suggestion
   * @return a Response Entity with HTTP Status OK and a list of the Role entries.
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/RoleController.java
> +    } catch ( RoleInvalidNameException e){
```suggestion
    } catch ( RoleInvalidNameException e)
    {
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/RoleController.java
> +    } catch ( RoleInvalidNameException e){
Just to keep it the same as the one above.

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/UserController.java
> +
```suggestion
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/UserController.java
> +   * @param authentication information about the currently authenticated user.
```suggestion
   * @param username - the username of the specific User.
   * @param authentication - information about the currently authenticated user.
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/UserController.java
> +   * @param authentication information about the currently authenticated user.
For better readability.

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/UserController.java
> +  @ResponseBody
```suggestion
  @ResponseBody
```
Is this needed ?

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/UserController.java
> +    List<GrantedAuthority> authorities = new ArrayList<>();
```suggestion
    // Security Check
    List<GrantedAuthority> authorities = new ArrayList<>();
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/UserController.java
> +      throw new ResponseStatusException( HttpStatus.NOT_FOUND, "PATCH: User Not Found", e );
```suggestion
    } catch ( UserNotFoundException e ) {
      throw new ResponseStatusException( HttpStatus.NOT_FOUND, "PATCH: User Not Found", e );
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/UserController.java
> +      throw new ResponseStatusException( HttpStatus.NOT_FOUND, "PATCH: User Not Found", e );
For consistency.

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/UserController.java
> +    } catch ( UserInvalidNameException e){
```suggestion
    } catch ( UserInvalidNameException e) {
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/UserController.java
> +      throw new ResponseStatusException( HttpStatus.BAD_REQUEST, "PATCH: Can not change username", e );
```suggestion
      throw new ResponseStatusException( HttpStatus.BAD_REQUEST, "PATCH: Cannot change username", e );
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/RoleService.java
> +   * @param entry the Role entry.
```suggestion
   * @param entry - the Role entry.
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/RoleService.java
> +   * @param entry the Role entry.
For clarity.

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/RoleService.java
> +   * @param entry the Role entry.
```suggestion
   * @param entry - the Role entry.
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/RoleService.java
> +      throw new RoleInvalidNameException("Method update: Name Field Can't Be Null");
```suggestion
      throw new RoleInvalidNameException("Method update: Name field can't be null.");
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/RoleService.java
> +      throw new RoleInvalidNameException("Method update: Name Field Can't Be Null");
This way it matches the one from `add` method.

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/RoleService.java
> +      throw new RoleNotFoundException("Method delete: Role Not Found");
```suggestion
      throw new RoleNotFoundException("Method delete: Role not found.");
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +    log.info("User {} found in te database", username);
```suggestion
    log.info("User {} found in the database", username);
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +    log.info("Fetching user {}", username);
Would be nice to add these logs throughout the entire class.

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +    return users;
```suggestion
    return userRepository.findAllByRolesContaining(roleName);
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +   * @param entry the User entry.
```suggestion
   * @param entry - the User entry.
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +   * @param entry the User entry.
```suggestion
   * @param entry - the User entry.
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +   * @param entry the User entry.
```suggestion
   * @param entry - the User entry.
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +      throw new UserInvalidNameException("Method update: Name Field Can't Be Null");
```suggestion
      throw new UserInvalidNameException("Method update: Name field can't be null.");
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +    log.info(String.valueOf(userToUpdate.getUsername().equals(entry.getUsername())));
```suggestion
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +      throw new UserUsernameNotAllowedException("Method update: Can not change username.");
```suggestion
      throw new UserUsernameNotAllowedException("Method update: Cannot change username.");
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +      throw new UserNotFoundException("Method delete: User Not Found");
```suggestion
      throw new UserNotFoundException("Method delete: User not found.");
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +   * Add the Role to User entry given by user
```suggestion
   * Adds the Role to User entry given by user
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +    user.getRoles().add(role);
Make custom `getter` & `setter` for this one to add encapsulation.

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/JWTService.java
> +  private Date refresh_timer =  new Date(System.currentTimeMillis() + 24 * 60 * 60 * 1000);
```suggestion
  private Date accessTimer =  new Date(System.currentTimeMillis() + 24 * 60 * 60 * 1000);
  private Date refreshTimer =  new Date(System.currentTimeMillis() + 24 * 60 * 60 * 1000);
```
Refactor these variables to use *camelCase*.

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/JWTService.java
> +   * ased on the given token, using the algorithm
```suggestion
   * based on the given token, using the algorithm
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/JWTService.java
> +   * Generates a decoded JWT with informations about the authenticated user
```suggestion
   * Generates a decoded JWT with information on the authenticated user
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/security/UserSecurity.java
> +   * @param id the id of the specific user
```suggestion
   * @param id - the id of the specific user
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/filter/CustomAuthenticationFilter.java
> + *Creates a filter for the process of authentication
```suggestion
 * Creates a filter for the process of authentication
```

2021-09-23 18:42 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/security/SecurityConfig.java
> +    http.authorizeRequests().antMatchers(HttpMethod.GET, "/users/username").permitAll();
```suggestion
    // Custom authorization implemented in UserController.
    http.authorizeRequests().antMatchers(HttpMethod.GET, "/users/username").permitAll();
```

2021-09-23 18:43 UTC, CristiPV requested changes

2021-09-23 18:43 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/security/SecurityConfig.java
> +    customAuthenticationFilter.setFilterProcessesUrl("/users/login");
Add a custom endpoint for logging out as well.

2021-09-24 15:46 UTC, MarianGiugioiu commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/UserController.java
> +  @ResponseBody
No, it was deleted.

2021-09-24 15:54 UTC, MarianGiugioiu commented on apps/java-api/src/main/java/org/scoalaonline/api/DTO/RegisterForm.java
> +  private String Name;
Done. The getters and setters had the same name for both 'Name' and 'name'.

2021-09-25 17:16 UTC, CristiPV requested changes

2021-09-25 17:16 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/filter/CustomAuthenticationFilter.java
> +    log.info("Password is {}", password);
```suggestion
    log.info("Password is {}", password);
```

2021-09-25 17:16 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/filter/CustomAuthenticationFilter.java
> +    log.info("Password is {}", password);
Password should not be logged.

2021-09-25 17:16 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +   * Retrieves User entry with given username
```suggestion
   * Retrieves User entry with given the username
```

2021-09-25 17:16 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +   * Creates Spring Security UserDetails based on User entry
```suggestion
   * Creates Spring Security UserDetails based on the User entry
```

2021-09-25 17:16 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +    );
```suggestion
    User user = userRepository.findByUsername(username).orElseThrow(
      () -> {
        log.error("Username not found.");
        return new UsernameNotFoundException("Method loadUserByUsername: Username not found.");
      }
    );
```

2021-09-25 17:16 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
> +      log.error("User not found in te database.");
```suggestion
      log.error("User not found in the database.");
```

2021-09-25 17:16 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/service/RoleService.java
> +      log.error("Role not found in te database.");
```suggestion
      log.error("Role not found in the database.");
```

2021-09-25 17:16 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/RoleController.java
> +   * @param id the id of the Role to be deleted.
```suggestion
   * @param id - the id of the Role to be deleted.
```

2021-09-25 17:16 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/RoleController.java
> +   * @param id the id of the Role to be updated.
```suggestion
   * @param id - the id of the Role to be updated.
```

2021-09-25 17:16 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/RoleController.java
> +   * @param role the Role to be added in the db.
```suggestion
   * @param role - the Role to be added in the db.
```

2021-09-25 17:16 UTC, CristiPV commented on apps/java-api/src/main/java/org/scoalaonline/api/controller/RoleController.java
> +   * @param id the id of the specific Role
```suggestion
   * @param id - the id of the specific Role
```

2021-09-25 19:36 UTC, CristiPV approved these changes

2021-09-25 19:37 UTC, merged